# This is a basic workflow to help you get started with Actions

name: Build Container

on:
  push:
    paths:
      - '.devcontainer/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Image Name
        id: imagename
        run: echo "::set-output name=name::${{ env.REGISTRY }}/${GITHUB_REPOSITORY,,}/codespace"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .devcontainer/
          file: .devcontainer/Dockerfile.ghcr
          push: true
          tags: ${{ steps.imagename.outputs.name }}:latest
