# This is a basic workflow to help you get started with Actions

name: Build Container

on:
  push:
    paths:
      - '.devcontainer/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  texlive:
    name: Install texlive
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          config: .github/buildkit.toml

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Image Name
        id: imagename
        run: echo "::set-output name=name::${{ env.REGISTRY }}/${GITHUB_REPOSITORY,,}/codespace-base"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .devcontainer/
          file: .devcontainer/Dockerfile.texlive
          pull: true
          push: true
          tags: ${{ steps.imagename.outputs.name }}:latest
          cache-to: type=registry,mode=max,ref=${{ steps.imagename.outputs.name }}:cache
          cache-from: type=registry,ref=${{ steps.imagename.outputs.name }}:cache

  install:
    name: Install Other Dependencies
    needs: [texlive]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          config: .github/buildkit.toml

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Image Name
        id: imagename
        run: echo "::set-output name=name::${{ env.REGISTRY }}/${GITHUB_REPOSITORY,,}/codespace"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .devcontainer/
          file: .devcontainer/Dockerfile.ghcr
          pull: true
          push: true
          tags: ${{ steps.imagename.outputs.name }}:latest
          cache-to: type=registry,mode=max,ref=${{ steps.imagename.outputs.name }}:cache
          cache-from: type=registry,ref=${{ steps.imagename.outputs.name }}:cache
